name: Test, Build, and Deploy

on:
  push:
    branches:
    - master
    
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: install node
        uses: actions/setup-node@v1
      - name: install npm deps
        run: npm ci

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: run tests
        run: npm test

  bundle:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: bundle into dist
        run: npm run bundle
      - name: preserve artifacts
        uses: actions/upload-artifact@v1
          with:
            name: dist
            path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: bundle
    steps:
      - name: restore artifacts
        uses: actions/download-artifact@v1
          with:
            name: dist
            path: dist
      - name: deploy to firebase
        uses: w9jds/firebase-action@v1.0.1
          with:
            args: deploy --only hosting -p dist
          env:
            PROJECT_ID: tjandpals-whats-this
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}