name: Test, Build, and Deploy

on:
  push:
    branches:
    - master
    
jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: install node
        uses: actions/setup-node@v1
      - name: install npm deps
        run: npm ci
      - name: run tests
        run: npm test
      - name: bundle into dist
        run: npm run bundle
      - name: deploy to firebase
        uses: w9jds/firebase-action@v1.0.1
        with:
          args: deploy --only hosting
        env:
          PROJECT_ID: tjandpals-whats-this
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}