name: Test, Build, and Deploy

on:
  push:
    branches:
    - master
    
jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: install node
        uses: actions/setup-node@v1
      - name: install npm deps
        run: npm ci
      - name: run tests
        run: npm test
      - name: bundle into dist
        run: npm run bundle
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: dist 
          path: dist 
      - name: post to slack
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()
  deploy:
    runs-on: ubuntu-latest
    needs: bundle
    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: download artifacts
        uses: actions/download-artifact@master
        with:
          name: dist 
          path: dist 
      - name: deploy to firebase
        uses: w9jds/firebase-action@v1.0.1
        with:
          args: deploy --only hosting
        env:
          PROJECT_ID: tjandpals-whats-this
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: post to slack
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()